dist: trusty
language: java
cache:
  directories:
  - $HOME/.gradle
jdk:
- oraclejdk8
script: ./gradlew check
deploy:
- provider: script
  script: "./gradlew artifactoryPublish"
  on:
    branch: master
